spring:
  application:
    name: Copy Plus
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./db/copy-plus.db;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE
      driver-class-name: org.h2.Driver
      username: copy-plus
      password: copy-plus
  jpa:
    database: h2
    hibernate:
      ddl-auto: update



